version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: black_list_app      
    DEFAULT_REGION: us-east-2
    AWS_ACCOUNT_ID: 723237626566             

phases:
  install:
    commands:
      - echo "== INSTALL =="
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pytest

  pre_build:
    commands:
      - echo "== PRE-BUILD =="
      - export AWS_REGION=${AWS_DEFAULT_REGION:-$DEFAULT_REGION}
      - export REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - export IMAGE_TAG=${CODEBUILD_BUILD_NUMBER:-latest}
      - echo Logging into ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPO_URI

  build:
    commands:
      - echo "== TESTS =="
      - export SECRET_KEY="${SECRET_KEY:-u16af09a4848fd6373dd23e36d3446b486d0873515b5bcec3535946c7940ab78d}"
      - pytest -q
      - echo "== BUILD IMAGE =="
      - docker build -t $REPO_URI:$IMAGE_TAG -t $REPO_URI:latest .

  post_build:
    commands:
      - echo "== PUSH IMAGE =="
      - docker push $REPO_URI:$IMAGE_TAG
      - docker push $REPO_URI:latest
      - echo "== GENERATING imagedefinitions.json =="
      - printf '[{"name":"BlackListApp","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
      - echo "== GENERATING appspec.yaml =="
      - |
        cat > appspec.yaml <<EOF
        version: 0.0
        Resources:
          - TargetService:
              Type: AWS::ECS::Service
              Properties:
                TaskDefinition: <TASK_DEFINITION>
                LoadBalancerInfo:
                  ContainerName: BlackListApp
                  ContainerPort: 5000
        EOF
      - cat appspec.yaml
      - cat taskdef.json

artifacts:
  files:
    - appspec.yaml
    - taskdef.json
    - imagedefinitions.json
  name: BuildArtifact
