version: 0.2

phases:
<<<<<<< HEAD
  pre_build:
    commands:
      - pip install -r requirements.txt
artifacts:
  files:
    - '**/*'
=======
  install:
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pytest
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 930800958862.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Running tests..."
       pytest -q
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t repo-ecr-entrega-2 .
      - docker tag repo-ecr-entrega-2:latest 930800958862.dkr.ecr.us-east-1.amazonaws.com/repo-ecr-entrega-2:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 930800958862.dkr.ecr.us-east-1.amazonaws.com/repo-ecr-entrega-2:latest
artifacts:
  files:
    - '**/*'
>>>>>>> fa88c75f3cb2b272fc398c0149ed3e2af95bf329
