version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: black_list_app      
    DEFAULT_REGION: us-east-2
    AWS_ACCOUNT_ID: 723237626566             

phases:
  install:
    commands:
      - echo "== INSTALL =="
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pytest

  pre_build:
    commands:
      - echo "== PRE-BUILD =="
      - export AWS_REGION=${AWS_DEFAULT_REGION:-$DEFAULT_REGION}
      - export REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - export IMAGE_TAG=${CODEBUILD_BUILD_NUMBER:-latest}
      - echo Logging into ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPO_URI

  build:
    commands:
      - echo "== TESTS =="
      - pytest -q
      - echo "== BUILD IMAGE =="
      - docker build -t $REPO_URI:$IMAGE_TAG -t $REPO_URI:latest .

  post_build:
    commands:
      - echo "== PUSH IMAGE =="
      - docker push $REPO_URI:$IMAGE_TAG
      - docker push $REPO_URI:latest

      - echo "== GENERATING taskdef-output.json =="
      - sed "s|<IMAGE1_NAME>|$REPO_URI:$IMAGE_TAG|g" taskdef.json > taskdef-output.json

      - echo "== GENERATING appspec-output.yaml =="
      - cat > appspec-output.yaml << 'EOF'
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: REPLACEME
        LoadBalancerInfo:
          ContainerName: BlackListApp
          ContainerPort: 5000
EOF

      - sed -i "s|REPLACEME|$REPO_URI:$IMAGE_TAG|g" appspec-output.yaml

artifacts:
  files:
    - appspec-output.yaml
    - taskdef-output.json
  name: BuildArtifact
  discard-paths: yes
