version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: repo-ecr-entrega-2      
    DEFAULT_REGION: us-east-1             

phases:
  install:
    commands:
      - set -e
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pytest
  pre_build:
    commands:
      - set -e
      - export AWS_REGION=${AWS_DEFAULT_REGION:-$DEFAULT_REGION}
      - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - export REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - export IMAGE_TAG=${CODEBUILD_BUILD_NUMBER:-latest}
      # Para los tests 
      - export SECRET_KEY="${SECRET_KEY:-u16af09a4848fd6373dd23e36d3446b486d0873515b5bcec3535946c7940ab78d}"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo "Running tests..."
      - pytest -q
      - echo "Building image..."
      - docker build -t $REPO_URI:$IMAGE_TAG -t $REPO_URI:latest .
  post_build:
    commands:
      - echo "Pushing image..."
      - docker push $REPO_URI:$IMAGE_TAG
      - docker push $REPO_URI:latest
      - echo "OK"
